### ISSUE TITLE
Feature Request: Ability to Reorder Notes

### ISSUE THREAD

**Issue by arberiii** [computing-den/unforget#13]
I am a user of Unforget. I appreciate the simplicity and security of the application. However, I believe that the usability of the app could be significantly enhanced by adding the ability to reorder notes in UI.

Current Behavior:
Currently, notes are displayed in the order they were created, and there is no way to change their order manually. This can make it difficult to organize notes in a preferred sequence, especially for users who rely on a specific order for better workflow and accessibility.

Desired Behavior:
I would like to request a feature that allows users to manually reorder their notes. This could be implemented via a drag-and-drop interface, where users can click and hold a note, then drag it to their desired position within the list. Alternatively, providing an option to move notes up or down in the list via buttons or context menu options would also be helpful.

**Comment by computing-den** [comment]
I fully agree and it seems to be the most requested feature. I have it planned for the next release coming soon.

**Comment by computing-den** [comment]
The new version is published. On mobile, there's a button in the toolbar that activates selection mode and on desktop, you can hover your mouse on the notes to see the selection area.
