### ISSUE TITLE
Synced note not available in all clients.

### ISSUE THREAD

**Issue by germanh1982** [computing-den/unforget#8]
Hi

I'm using unforget with the sync feature. I have three clients synced with my account (my Android phone and two computers, all running Firefox).

There's a particular note in one of my clients (phone) that doesn't seem to appear in the general list in the other two clients:

https://unforget.computing-den.com/n/3ddad039-e572-43e9-8e4a-8105aa7a1e8c

I did try doing "Full sync" in all the clients involved several times, to no avail. In the affected clients, the note doesn't show if I search a part of the title in the filter box, but it does show if I enter the link above manually (copied from my mobile phone).

How could I further diagnose this particular issue?
Thanks in advance
German

**Comment by computing-den** [comment]
Hi

First, please make sure that if the note is pinned, in the affected clients, in the general list, the "show pinned notes" button is on. If that is off, even during search it will not appear.

If that doesn't solve it, in the affected clients, could you open the firefox Web Developer Tools (Ctrl+Shift+I) -> Storage -> Indexed DB -> notes (as shown in the screenshot) and see if you can find that note (key: "3ddad039-e572-43e9-8e4a-8105aa7a1e8c").

If you find it, please click on it to see the details on the right hand side. If you could please copy the details here (minus the text of course) I'd appreciate it.

![Screenshot from 2024-06-18 16-37-49](https://github.com/computing-den/unforget/assets/162131707/8f0255ed-967e-401d-9286-abb4d4a0e145)

**Comment by germanh1982** [comment]
Well.. it was the "pinned" suggestion what caused the note not to show in the normal list.

Thank you for your prompt reply, and sorry for the inconvenience!!
Best regards, German

**Comment by computing-den** [comment]
Your welcome. I think the show/hide pinned notes feature can be a little confusing. Sometimes I forget to turn it on/off especially during search as well. I think I'll add a little reminder at the top like "10 pinned notes found. Click here to show."  Please let me know if you have any suggestions.

Best regards,
Sean

**Comment by germanh1982** [comment]
In my opinion is just a matter of habits.

I recently migrated to unforget from Google Keep so I'm just getting to know this tool. In Keep, the pinning of the notes only cause them to show above the unpinned ones, so that's what I was accustomed to, but the way is implemented here is valid as well.

A reminder like suggested could be helpful for newbies like myself :)

Thank you for your work
German
